Update pr-check.yml

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -15,6 +15,5 @@ jobs:
 
     - name: Install dependencies
       run: |
-        echo "message=Installing-Dependencies" >> $GITHUB_OUTPUT
-        echo "::error file=test" >> $GITHUB_OUTPUT
+        echo "::error::Filename doesn't match possible files" || exit 1
       shell: bash
